# Generated by Django 5.2.1 on 2025-06-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m/%d/'),
        ),
    ]
