# Generated by Django 5.2.1 on 2025-06-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apis.employee',),
        ),
    ]
